InstaKiloGram/urls.py
"""
Definition of urls for InstaKiloGram.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm
import settings
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
   
    url(r'^$', 'app.views.home', name='home'),
    url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'',include('app.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT);

app/urls.py
from django.conf.urls import url
from . import views
urlpatterns=(
    url(r'^items/$',views.view_items,name='item_list'),
    url(r'^items/(?P<id>\d+)$',views.item_detail,name='item_detail'),
    url(r'^items/(?P<id>\d+)$',views.photo_detail,name='photo_detail'),
    url(r'^createalbum/$',views.create_album,name='create_album'),
    url(r'^photos/(?P<id>\d+)/addphoto/$',views.add_photo,name='add_photo'),
    url(r'^delete/(?P<id>\d+)/$',views.delete_album,name='del_album')
)

app/models.py
"""
Definition of models.
"""

from django.db import models
from django.core.urlresolvers import reverse
from gallery import ThumbnailImageField  
# Create your models here.

class Item(models.Model):
    """An Item is like an Album, it represent a set of photos"""
    name=models.CharField(max_length=150)
    description=models.TextField()
    
    class Meta:
        ordering=['name']
        
    def __str__(self):
         return self.name
    def __unicode__(self):
         return self.name
    
    def get_absolute_url(self):
        return reverse('item_detail',args=[self.id])
 
class Photo(models.Model):
     """ Model for an photo element"""
     item=models.ForeignKey('Item',on_delete=models.CASCADE)
     title=models.CharField(max_length=250)
     image=ThumbnailImageField(upload_to='photos')
     caption=models.CharField(max_length=250,blank=True)
     created=models.DateTimeField(auto_now=True)
     updated=models.DateTimeField(auto_now_add=True)
     
     class Meta:
         ordering=['title']
     
     def __str__(self):
         return self.title
     def __unicode__(self):
         return self.title
         
     def get_absolute_url(self):
         return reverse('photo_detail',args=[self.id])
    

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from models import Item,Photo
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

class AlbumForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=('name','description')
    def __init__(self,*args,**kwargs):
        super(AlbumForm,self).__init__(*args,**kwargs)
        self.helper=FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-md-offset-1 col-md-2'
        self.helper.field_class='col-md-6'
        self.helper.add_input(Submit('submit','Create'))

class PhotoForm(forms.ModelForm):
    class Meta:
        model=Photo
        fields=('title','caption','image','caption')
    def __init__(self,*args,**kwargs):
        super(PhotoForm,self).__init__(*args,**kwargs)
        self.helper=FormHelper()
        self.helper.form_class='form-horizontal'
        self.helper.label_class='col-md-offset-1 col-md-2'
        self.helper.field_class='col-md-6'
        self.helper.add_input(Submit('submit','Create'))
    

app/views.py
"""
Definition of views.
"""

from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpRequest,HttpResponseRedirect
from django.template import RequestContext
from datetime import datetime
from models import Item,Photo
from forms import AlbumForm,PhotoForm
from django.core.urlresolvers import reverse
def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    all_items=Item.objects.all()
    
    return render(request,'app/index.html',{'title':'InstaKiloGram','year':datetime.now().year,'all_items':all_items})

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(  
        request,
        'app/contact.html',
        context_instance = RequestContext(request,
        {
            'title':'Contact',
            'message':'Your contact page.',
            'year':datetime.now().year,
        })
    )

def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/about.html',
        context_instance = RequestContext(request,
        {
            'title':'About',
            'message':'Your application description page.',
            'year':datetime.now().year,
        })
    )

def view_items(request):
    all_items=Item.object.all()
    thumbnail=all_items.photo_set().first().image.thumb_url
    return render(request,'app/index.html',{'all_items':all_items,'thumbnail':thumbnail})
    
def item_detail(request,id):
    album=get_object_or_404(Item,id=id)
    images=album.photo_set.all()
    
    return render(request,'app/ItemDetails.html',{'album':album,'images':images})
    
def add_photo(request,id):
    album=get_object_or_404(Item,id=id)
    if request.method=='POST':
        form=PhotoForm(request.POST,request.FILES  )
        if form.is_valid():
            instance=form.save(commit=False)
            instance.item=album
            instance.save()
            return redirect(reverse('home'))
    form=PhotoForm()
    return render(request,'app/AddPhoto.html',{'form':form})
        
def photo_detail(request):
    return HttpResponse("<h1>Photots</h1>")

def create_album(request):
    form=AlbumForm(request.POST or None)
    if form.is_valid():
        form.save()
        #use reverse always with the HttpResponseRedirect
        return HttpResponseRedirect(reverse('home'))
    return render(request,'app/createform.html',{'form':form})        

def delete_album(request,id):
    item=get_object_or_404(Item,id=id)
    for photos in item.photo_set.all():
        photos.image.delete()
    item.delete()
    return HttpResponseRedirect(reverse('home'))

app/templates/app/AddPhoto.html
{% extends "app/layout.html" %}
{%  load crispy_forms_tags %}
{% block content %}

<div class=" row container " style="margin-top:30px" >        
    <div class="col span-1-of-2" >      
        <form class="form-horizontal " method="post" enctype="multipart/form-data" >
                {% csrf_token %}
            <div class="form-input"> 
                    <input class="text-input" id="id_title" maxlength="250" name="title" type="text" placeholder="Name"> 
            </div>
            <div class="form-input">
                <input class="text-input " id="id_caption" maxlength="250" name="caption" type="text" placeholder="Caption"> 
            </div>
            <div class="clearablefileinput btn-submit"> 
                <span>Choose File</span>
                <input  id="id_image" name="image" type="file"> 
            </div>
            <input type="submit" name="submit" value="Create" class="btn-submit" id="submit-id-submit">     
        </form>        
    </div>
</div>



                          

{% endblock %}

app/templates/app/ItemDetails.html
{% extends "app/layout.html" %}
{% block content %}

<div class="row " >
    <div class="header-photo" >
        <h2>{{album.name}}</h2>
        <h3>{{album.description}}</h3>
    </div>
</div>
<div class ="container" >
    <div class="row" >
        {% for photo in images %}
        <div class="col span-1-of-3" >
            <div class="panel">
                <img class="image" src="{{photo.image.url}}" alt="Responsive image">
                <div class="photo-text" >
                    <h3>{{ photo.title }}</h3>
                    <p>{{ photo.caption }}</p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}

                        </div>
                        <div class="row">

        {% endif %}
        {% endfor %}
    </div>
</div>

<div class="float-btn" >
    <a href="{% url 'add_photo' album.id %}"><i class="ion-android-add icon-big" ></i></a>
</div>

<div id="Mymodal"  class="modal">
            <span class="close" id ="close" >&times;</span>
            <!-- Modal Content (The Image) -->
            <img class="modal-content" id="img01">

            <!-- Modal Caption (Image Text) -->
            <div id="caption"></div>
            
            
</div>

{% endblock %}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/createform.html
{% extends "app/layout.html" %}
{%  load crispy_forms_tags %}
{% block content %}

<div class=" row container " style="margin-top:30px" >        
    
     <div class="col span-1-of-2" >    
        <form class="form-horizontal " method="post">
            {% csrf_token %}
            <div class="form-input" >
                <input class="text-input"  type="text" name="name" id="id_name" placeholder="Enter Name Of Folder "  >
            </div>
            <div class="form-input" >
                <textarea class="text-input"  name="description" id="id_description" placeholder="enter some detail" ></textarea>
            </div>
            <input class="btn-submit" type="submit" value="create" >
        </form>
     </div>        
   
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

 <div class="items">
                <div class="row" >
                    {% for item in all_items  %}

                    <div class="col span-1-of-3">
                        <div class="add add-up" >
                            <a href ="{% url 'del_album' item.id %}"> <i  class=" ion-android-close icon "></i></a>
                        </div>
                        <div class="card-container">
                            <div class="content" >
                            <h2>{{ item.name }}</h2>
                            <p>{{ item.description }}</p>
                            </div>
                                
                        </div>
                        <div class="add add-below" >
                           <a href ="{% url 'item_detail' item.id %}"> <i class="ion-android-arrow-forward icon"></i></a>  
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}

                        </div>
                        <div class="row">

                    {% endif %}
                    {% endfor %}
                </div>
 </div>

<div class="float-btn" >
             <a href="{% url 'create_album' %}"><i class="ion-android-add icon-big" ></i></a>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ title }} - My Django Application</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/grid.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />   
        <link rel="stylesheet" type="text/css" href="{% static 'css/ionicons-2.0.1/css/ionicons.min.css' %}" />
        
    </head>

 <body>
        <header class="header clearfix">
            <nav class="clearfix" >
                <div class="brand" >
                  <a href="{% url 'home' %}"> <h3>  Instakilogram </h3></a>
                </div>                
                <div class="navigation">
                    
                    <ul>
                        <li><a href="{% url 'about' %}">About</a></li>
                        <li><a href="{% url 'contact' %}">Contact </a></li>
                        <li> <a href="#">Register </a></li>
                        <li> <a href="#">Login </a></li>
                    </ul>
                </div>
            </nav>
        </header>
    <div class="container body-content">
{% block content %}{% endblock %}
       
   
{% block scripts %}
    <script src="{% static 'scripts/jquery.min.js' %}"></script>
    <script src="{% static 'scripts/site.js' %}"></script>
{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>  v                                            
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}